// main.js — reads apps.js and renders cards into the grid
// DO NOT EDIT THIS FILE. Edit apps.js to add or update apps.

document.addEventListener('DOMContentLoaded', () => {
  const grid = document.getElementById('app-grid');
  if (!grid || !Array.isArray(apps) || apps.length === 0) return;

  apps.forEach(app => {
    const article = document.createElement('article');
    article.className = 'app-card';

    article.innerHTML = `
      <a href="${app.url}" target="_blank" rel="noopener noreferrer" class="card-link">
        <div class="card-screenshot">
          <img src="${app.screenshot}" alt="${app.name} screenshot" loading="lazy" />
          <div class="card-overlay"></div>
        </div>
        <div class="card-body">
          <h2 class="card-name">${app.name}</h2>
          <p class="card-description">${app.description}</p>
          <span class="card-cta">View app <span class="cta-arrow">→</span></span>
        </div>
      </a>
    `;

    grid.appendChild(article);
  });
});
